export const LIKED = "LIKED";
export const MATCHED = "MATCHED";
export const GOT_FRIEND_REQUEST = "GOT_FRIEND_REQUEST";
export const CONFIRMED_FRIEND_REQUEST = "CONFIRMED_FRIEND_REQUEST";
export const DECLINED_FRIEND_REQUEST = "DECLINED_FRIEND_REQUEST";
export const BLOCKED = "BLOCKED";
export const UNBLOCKED = "UNBLOCKED";
