export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
export const SET_USER_MESSAGES = "SET_USER_MESSAGES";

export const GET_ALL_MESSAGES_REQUEST = "GET_ALL_MESSAGES_REQUEST";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_FAIL = "GET_ALL_MESSAGES_FAIL";
