export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
export const SET_USER_MESSAGES = "SET_USER_MESSAGES";

export const GET_ALL_MESSAGES_REQUEST = "GET_ALL_MESSAGES_REQUEST";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_FAIL = "GET_ALL_MESSAGES_FAIL";

export const GET_CHAT_LIST_USERS_REQUEST = "GET_CHAT_LIST_USERS_REQUEST";
export const GET_CHAT_LIST_USERS_SUCCESS = "GET_CHAT_LIST_USERS_SUCCESS";
export const GET_CHAT_LIST_USERS_FAIL = "GET_CHAT_LIST_USERS_FAIL";

export const SET_USER_MESSAGES_REQUEST = "SET_USER_MESSAGES_REQUEST";
export const SET_USER_MESSAGES_SUCCESS = "SET_USER_MESSAGES_SUCCESS";
export const SET_USER_MESSAGES_FAIL = "SET_USER_MESSAGES_FAIL";

export const SET_RANDOM_USERS_REQUEST = "SET_RANDOM_USER_REQUEST";
export const SET_RANDOM_USERS_SUCCESS = "SET_RANDOM_USER_SUCCESS";
export const SET_RANDOM_USERS_FAIL = "SET_RANDOM_USER_FAIL";

export const SET_USER_OFFLINE = "SET_USER_OFFLINE";

export const SET_CHAT_LIST_USER_OFFLINE = "SET_CHAT_LIST_USER_OFFLINE";

export const SET_FRIENDS = "SET_FRIENDS";
export const SET_BLOCKED = "SET_BLOCKED";

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL";

export const DELETE_ALL_MESSAGES_REQUEST = "DELETE_ALL_MESSAGES_REQUEST";
export const DELETE_ALL_MESSAGES_SUCCESS = "DELETE_ALL_MESSAGES_SUCCESS";
export const DELETE_ALL_MESSAGES_FAIL = "DELETE_ALL_MESSAGES_FAIL";

export const SET_EMPTY_MESSAGE = "SET_EMPTY_MESSAGE";
